services:
  db:
    image: mariadb:10.4
    container_name: db_server
    environment:
      MYSQL_ROOT_PASSWORD: Akiokapass0
      MYSQL_DATABASE: akioka_db
      MYSQL_USER: akioka_administrator
      MYSQL_PASSWORD: Akiokapass0
    networks:
      - app_network
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_server
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - db
    environment:
      DB_HOST: db_server
      DB_DATABASE: akioka_db
      DB_USERNAME: akioka_administrator
      DB_PASSWORD: Akiokapass0
    volumes:
      - ./html:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_server
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app_network
      
  python:
    image: python:3.9
    container_name: python_server
    networks:
      - app_network
    volumes:
      - ./python:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    stdin_open: true
    command: >
      /bin/bash -c "pip install -r requirements.txt && python main.py"

networks:
  app_network:
    driver: bridge